# Generated by Django 3.1.1 on 2021-04-26 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210415_2325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fryzjer',
            name='salon',
        ),
        migrations.AddField(
            model_name='salon',
            name='fryzjer',
            field=models.ManyToManyField(related_name='fryzjer', to='main.Fryzjer'),
        ),
        migrations.AddField(
            model_name='salon',
            name='wlasciciel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wlasciciel', to='main.fryzjer'),
        ),
    ]
