# Generated by Django 3.1.1 on 2021-04-26 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210426_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='fryzjer',
            name='nr_tel',
            field=models.CharField(default='no number', max_length=20),
        ),
        migrations.AddField(
            model_name='salon',
            name='nr_tel',
            field=models.CharField(default='no number', max_length=20),
        ),
    ]
