# Generated by Django 3.2 on 2021-05-07 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210426_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='godzina_otwarcia',
            field=models.CharField(default='Brak', max_length=10),
        ),
        migrations.AddField(
            model_name='salon',
            name='godzina_zamkniecia',
            field=models.CharField(default='Brak', max_length=10),
        ),
    ]
