# Generated by Django 3.2 on 2021-05-10 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210507_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='klient',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='static/ocen_fryzjera/avatars/'),
        ),
    ]
