# Generated by Django 3.2 on 2021-05-10 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_klient_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klient',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='main/static/ocen_fryzjera/avatars/klients/'),
        ),
    ]
