# Generated by Django 3.2 on 2021-05-10 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_klient_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='fryzjer',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='main/static/ocen_fryzjera/avatars/fryzjers/'),
        ),
    ]
