# Generated by Django 3.1.1 on 2021-05-10 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_fryzjer_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='fryzjer',
            name='invite_received',
            field=models.ManyToManyField(blank=True, related_name='invites_received', to='main.Fryzjer'),
        ),
        migrations.AddField(
            model_name='fryzjer',
            name='invite_sent',
            field=models.ManyToManyField(blank=True, related_name='invites_sent', to='main.Fryzjer'),
        ),
        migrations.AddField(
            model_name='fryzjer',
            name='invites',
            field=models.ManyToManyField(related_name='_fryzjer_invites_+', to='main.Fryzjer'),
        ),
    ]
