# Generated by Django 3.1.1 on 2021-05-15 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20210515_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='salonrelationship',
            name='fryzjerID',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
