# Generated by Django 3.2 on 2021-05-24 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20210524_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ocena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True, null=True)),
                ('tresc', models.CharField(max_length=300, null=True)),
                ('liczba_gwiazdek', models.IntegerField(default=0, null=True)),
                ('fryzjer', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.fryzjer')),
                ('klient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.klient')),
                ('salon', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.salon')),
            ],
        ),
    ]
