# Generated by Django 3.2 on 2021-05-24 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_ocena'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='liczba_ocen',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salon',
            name='srednia_ocena',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
