# Generated by Django 3.2 on 2021-06-11 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20210524_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='fryzjer',
            name='bio',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
