# Generated by Django 3.2 on 2021-06-12 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_fryzjer_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='zamowienie',
            name='klient',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.klient'),
        ),
        migrations.AlterField(
            model_name='fryzjer',
            name='bio',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
