# Generated by Django 3.2 on 2021-06-12 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20210612_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='zamowienie',
            name='fryzjer',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.fryzjer'),
        ),
    ]
