# Generated by Django 3.2 on 2021-06-16 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_zamowienie_fryzjer'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='main/static/ocen_fryzjera/avatars/salony/'),
        ),
    ]
