# Generated by Django 3.2 on 2021-06-16 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_salon_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fryzjer',
            name='avatar',
            field=models.ImageField(blank=True, default='main/static/ocen_fryzjera/default-avatar.jpg', null=True, upload_to='main/static/ocen_fryzjera/avatars/fryzjers/'),
        ),
    ]
