# Generated by Django 3.2 on 2021-06-16 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_fryzjer_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fryzjer',
            name='bio',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='fryzjer',
            name='invites',
            field=models.ManyToManyField(blank=True, null=True, related_name='_main_fryzjer_invites_+', to='main.Fryzjer'),
        ),
        migrations.AlterField(
            model_name='fryzjer',
            name='salon_to_add',
            field=models.ManyToManyField(blank=True, null=True, to='main.SalonRelationship'),
        ),
    ]
