# Generated by Django 3.2 on 2021-06-16 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20210616_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='bio',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
