# Generated by Django 3.2 on 2021-06-17 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_salon_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fryzjer',
            name='avatar',
            field=models.ImageField(default='main/static/ocen_fryzjera/avatars/fryzjers/default-avatar.jpg', upload_to='main/static/ocen_fryzjera/avatars/fryzjers/'),
        ),
    ]
