# Generated by Django 3.2 on 2021-06-17 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_fryzjer_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fryzjer',
            name='avatar',
            field=models.ImageField(blank=True, default='main/static/ocen_fryzjera/avatars/fryzjers/default-avatar.jpg', null=True, upload_to='main/static/ocen_fryzjera/avatars/fryzjers/'),
        ),
        migrations.AlterField(
            model_name='klient',
            name='avatar',
            field=models.ImageField(blank=True, default='main/static/ocen_fryzjera/avatars/klients/default-avatar.jpg', null=True, upload_to='main/static/ocen_fryzjera/avatars/klients/'),
        ),
        migrations.AlterField(
            model_name='salon',
            name='avatar',
            field=models.ImageField(blank=True, default='main/static/ocen_fryzjera/avatars/salony/default-image.jpg', null=True, upload_to='main/static/ocen_fryzjera/avatars/salony/'),
        ),
    ]
