# Generated by Django 3.2 on 2021-06-17 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20210617_0652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fryzjer',
            name='nr_tel',
            field=models.CharField(blank=True, default='no number', max_length=20, null=True),
        ),
    ]
