# Generated by Django 3.2 on 2021-06-17 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_auto_20210617_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fryzjer',
            name='bio',
            field=models.CharField(blank=True, default='Brak opisu', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='fryzjer',
            name='nr_tel',
            field=models.CharField(blank=True, default='Brak numeru', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fryzjer',
            name='srednia_ocena',
            field=models.FloatField(blank=True, default='Brak ocen', null=True),
        ),
        migrations.AlterField(
            model_name='salon',
            name='nazwa',
            field=models.CharField(default='Brak nazwy', max_length=50),
        ),
        migrations.AlterField(
            model_name='salon',
            name='nr_tel',
            field=models.CharField(default='Brak numeru', max_length=20),
        ),
        migrations.AlterField(
            model_name='salon',
            name='srednia_ocena',
            field=models.FloatField(blank=True, default='Brak ocen', null=True),
        ),
    ]
