# Generated by Django 3.2 on 2021-06-17 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_auto_20210617_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usluga',
            name='salon',
        ),
        migrations.AddField(
            model_name='usluga',
            name='salon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salon', to='main.salon'),
        ),
    ]
