# Generated by Django 3.1.7 on 2021-03-23 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(default='NoName', max_length=50)),
                ('NIP', models.CharField(max_length=25)),
                ('regon', models.CharField(max_length=25)),
                ('ulica', models.CharField(blank=True, max_length=50, null=True)),
                ('nr_lokalu', models.IntegerField(blank=True, default=0, null=True)),
                ('miasto', models.CharField(max_length=50)),
                ('kod_pocztowy', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Zamowienie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_zamowienia', models.CharField(max_length=80)),
                ('termin_uslugi', models.DateTimeField()),
                ('data_zamowienia', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('sent', 'sent'), ('accepted', 'accepted')], max_length=15)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.salon')),
            ],
        ),
        migrations.CreateModel(
            name='Usluga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=80)),
                ('opis', models.TextField(blank=True, null=True)),
                ('cena', models.FloatField()),
                ('min_czas', models.IntegerField(default=0)),
                ('max_czas', models.IntegerField(default=0)),
                ('salon', models.ManyToManyField(to='main.Salon')),
            ],
        ),
        migrations.CreateModel(
            name='Klient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staly_klient', models.BooleanField(default=False)),
                ('nr_telefonu', models.CharField(blank=True, max_length=20, null=True)),
                ('ulica', models.CharField(blank=True, max_length=50, null=True)),
                ('nr_domu', models.IntegerField(blank=True, default=0, null=True)),
                ('miasto', models.CharField(max_length=50)),
                ('kod_pocztowy', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Fryzjer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('srednia_ocena', models.FloatField(blank=True, null=True)),
                ('ulica', models.CharField(blank=True, max_length=50, null=True)),
                ('nr_domu', models.IntegerField(blank=True, default=0, null=True)),
                ('miasto', models.CharField(max_length=50)),
                ('kod_pocztowy', models.CharField(max_length=20)),
                ('salon', models.ManyToManyField(to='main.Salon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
