# Generated by Django 3.1.7 on 2021-03-23 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fryzjer',
            name='imie',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fryzjer',
            name='nazwisko',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='klient',
            name='imie',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='klient',
            name='nazwisko',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fryzjer',
            name='kod_pocztowy',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fryzjer',
            name='miasto',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='klient',
            name='kod_pocztowy',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='klient',
            name='miasto',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='klient',
            name='staly_klient',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='usluga',
            name='cena',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='usluga',
            name='max_czas',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='usluga',
            name='min_czas',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='usluga',
            name='nazwa',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='zamowienie',
            name='data_zamowienia',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='zamowienie',
            name='nazwa_zamowienia',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='zamowienie',
            name='termin_uslugi',
            field=models.DateTimeField(null=True),
        ),
    ]
