# Generated by Django 3.1.7 on 2021-04-15 21:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_auto_20210323_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klient',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='klient', to=settings.AUTH_USER_MODEL),
        ),
    ]
